name: ethio_trading_app
description: "An Ethiopian trading application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Firebase dependencies
  firebase_core: 2.4.1
  firebase_core_web: 2.1.0
  firebase_auth: 4.2.5
  firebase_auth_web: 5.2.4
  firebase_analytics: 10.1.0
  firebase_database: 10.0.9
  cloud_firestore: 4.3.1
  cloud_firestore_web: 3.2.1
  cloud_firestore_platform_interface: 5.10.1
  
  # UI and functionality
  cupertino_icons: ^1.0.5
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^21.2.4
  intl: ^0.17.0
  http: ^1.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  candlesticks: ^2.1.0
  websocket_universal: ^1.1.1
  device_info_plus: ^9.1.1
  crypto: ^3.0.3
  google_fonts: ^5.1.0
  animate_do: ^3.1.1
  flutter_animate: ^4.5.0
  timeago: 3.3.0
  location: ^5.0.3
  geolocator: ^10.1.0
  logging: ^1.2.0
  html: ^0.15.4
  url_launcher: ^6.2.2
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
