name: ethio_trading_app
description: "An Ethiopian trading application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_auth_web: ^5.14.0
  firebase_analytics: ^11.4.3
  cloud_firestore: ^5.6.4
  cupertino_icons: ^1.0.5
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  fl_chart: ^0.66.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
