name: ethio_trading_app
description: "An Ethiopian trading application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  firebase_auth_web: ^5.14.0
  firebase_analytics: ^11.4.3
  cloud_firestore: ^5.6.4
  cupertino_icons: ^1.0.5
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  syncfusion_flutter_charts: ^28.2.6
  intl: ^0.19.0
  http: ^1.1.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  candlesticks: ^2.1.0
  websocket_universal: ^1.1.1
  device_info_plus: ^9.1.1
  crypto: ^3.0.3
  google_fonts: ^5.1.0
  animate_do: ^3.1.1
  flutter_animate: ^4.5.0
  timeago: ^3.6.0
  location: ^5.0.3
  geolocator: ^10.1.0
  jiffy: ^6.2.1
  url_launcher: ^6.2.1
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

vars:
  port: 3000
  debugPort: 9101
